apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-seou
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-seou@sha256:3fae65861caf04fa0d2fb7f18c674f887b75e3c419ad5d3aef6854c6b89487ce
        name: my-nodejs
        resources: {}
status: {}
